name: SwornRPG
main: net.dmulloy2.swornrpg.SwornRPG
version: ${project.version} (Build ${project.build.number})
author: dmulloy2
description: The fully featured mcMMO Alternative
softdepend: [TagAPI, Essentials, Factions, SwornNations, Vault]
commands:
  abilities:
    description: Check SwornRPG ability levels
    usage: /<command> [player]
    aliases: [skills]
  addxp:
    description: Manually give xp to a player
    usage: /<command> <player> <xp>
    aliases: [givexp]
  adminchat:
    description: Talk in admin-only chat
    usage: /<command> <message>
    aliases: [a]
  adminsay:
    description: Alternate admin say command
    usage: /<command> message>
    aliases: [asay]
  coordstoggle:
    description: Toggle death coordinate messages
    usage: /<command>
  deny:
    description: Deny a player's proposal
    usage: /<command>
    aliases: [reject]
  divorce:
    description: Divorce your spouse
    usage: /<command>
  eject:
    description: Remove a player from your head
    usage: /<command>
  frenzy:
    description: Enter frenzy mode
    usage: /<command>
  hat:
    description: Put the block in your hand on your head
    usage: /<command> [remove]
  highcouncil:
    description: Talk in high council chat
    usage: /<command> <message>
    aliases: [hc]
  itemname:
    description: Set the name of your in-hand item
    usage: /<command> <name>
    aliases: [iname]
  level:
    description: Check a player's level
    usage: /<command> [player]
  marry:
    description: Marry another player
    usage: /<command> <player>
  match:
    description: Match a string with the closest player
    usage: /<command> <string>
    aliases: [matchplayer]
  propose:
    description: Propose marriage to a player
    usage: /<command> <player>
  resetlevel:
    description: Reset a player's level
    usage: /<command> [player]
    aliases: [levelr]
  ride:
    description: Get on a player's head
    usage: /<command> <player>
  sitdown:
    description: Sit in a chair
    usage: /<command>
    aliases: [sit]
  spouse:
    description: Check a player's spouse
    usage: /<command> [player]
  srpg:
    description: SwornRPG base command
    usage: /<command> <args>
    aliases: [swornrpg]
  stafflist:
    description: List online staff
    usage: /<command>
    aliases: [staff]
  standup:
    description: Get out of your chair
    usage: /<command>
    aliases: [stand]
  superpick:
    description: Activate super pickaxe
    usage: /<command>
    aliases: [mine, superpickaxe]
  tag:
    description: Change the color above your head
    usage: /<command> [player] <tag>
  tagreset:
    description: Reset a player's tag
    usage: /<command> [player]
    aliases: [tagr]
  unlimitedammo:
    description: Activate unlimited ammo ability
    usage: /<command>
  unride:
    description: Get off of a player's head
    usgae: /<command>

permissions:
  srpg.admin:
    description: Gives access to features meant for server admins
    default: false
    children:
      srpg.moderator: true
      srpg.cmd.addxp: true
      srpg.cmd.adminsay: true
      srpg.cmd.highcouncil: true
      srpg.cmd.itemname: true
      srpg.cmd.level.reset: true
      srpg.cmd.reload: true
      srpg.cmd.tag: true
      srpg.cmd.tag.others: true
      srpg.cmd.tag.reset: true
      srpg.cmd.tag.reset.others: true
      srpg.update.notify: true
  srpg.*:
    description: Just an alias for srpg.admin
    default: op
    children:
      srpg.admin: true
  srpg.moderator:
    description: Gives access to features meant for server moderators
    default: false
    children:
      srpg.guard: true
      srpg.cmd.match: true
      srpg.cmd.ride: true
      srpg.cmd.unride: true
  srpg.guard:
    description: Gives access to features meant for server guards
    default: false
    children:
      srpg.player: true
      srpg.cmd.adminchat: true
      srpg.staff: true
  srpg.player:
    description: Gives access to features meant for regular players
    default: true
    children:
      srpg.cmd.abilities: true
      srpg.cmd.abilities.others: true
      srpg.cmd.coordstoggle: true
      srpg.cmd.deny: true
      srpg.cmd.divorce: true
      srpg.cmd.eject: true
      srpg.cmd.frenzy: true
      srpg.cmd.hat: true
      srpg.cmd.leaderboard: true
      srpg.cmd.level: true
      srpg.cmd.level.others: true
      srpg.cmd.marry: true
      srpg.cmd.propose: true
      srpg.cmd.sitdown: true
      srpg.cmd.spouse: true
      srpg.cmd.spouse.others: true
      srpg.cmd.stafflist: true
      srpg.cmd.standup: true
      srpg.cmd.superpickaxe: true
      srpg.cmd.unlimitedammo: true
      srpg.cmd.version: true
  srpg.cmd.abilities:
    description: Allows checking of individual abilities
    default: true
  srpg.cmd.abilities.others:
    description: Allows checking of other players' abilities
    default: true
  srpg.cmd.addxp:
    description: Allows forced addition of xp
    default: false
  srpg.cmd.adminchat:
    description: Allows access to admin chat
    default: false
  srpg.cmd.adminsay:
    description: Allows access to '/asay'
    default: false
  srpg.cmd.coordstoggle:
    description: Allows access to '/coordstoggle'
    default: true
  srpg.cmd.deny:
    description: Allows access to '/deny'
    default: true
  srpg.cmd.divorce:
    description: Allows access to '/divorce'
    default: true
  srpg.cmd.eject:
    description: Allows access to '/eject'
    default: true
  srpg.cmd.frenzy:
    description: Allows access to '/frenzy'
    default: true
  srpg.cmd.hat:
    description: Allows access to '/hat' 
    default: true
  srpg.cmd.highcouncil:
    description: Allows access to high council chat
    default: false
  srpg.cmd.itemname:
    description: Allows access to '/itemname'
    default: false
  srpg.cmd.leaderboard:
    description: Allows access to '/srpg lb'
    default: true
  srpg.cmd.level:
    description: Allows checking of individual level
    default: true
  srpg.cmd.level.others:
    description: Allows checking of others' levels
    default: true
  srpg.cmd.level.reset:
    description: Allows access to '/resetlevel'
    default: false
  srpg.cmd.marry:
    description: Allows access to '/marry'
    default: true
  srpg.cmd.match:
    description: Allows access to '/match'
    default: true
  srpg.cmd.propose:
    description: Allows access to '/propose'
    default: true
  srpg.cmd.reload:
    description: Allows access to '/srpg reload' 
    default: false
  srpg.cmd.ride:
    description: Allows access to '/ride'
    default: false
  srpg.cmd.sitdown:
    description: Allows access to '/sitdown'
    default: true
  srpg.cmd.spouse:
    description: Allows checking of individual spouse
    default: true
  srpg.cmd.spouse.others:
    description: Allows checking of others' spouses
    default: true
  srpg.cmd.stafflist:
    description: Allows access to '/staff'
    default: true
  srpg.cmd.standup:
    description: Allows access to '/standup'
    default: true
  srpg.cmd.superpickaxe:
    description: Allows access to '/superpickaxe'
    default: true
  srpg.cmd.tag:
    description: Allows setting of individual tag
    default: false
  srpg.cmd.tag.others:
    description: Allows setting of others' tags
    default: false
  srpg.cmd.tag.reset:
    description: Allows resetting of individual tag
    default: false
  srpg.cmd.tag.reset.others:
    description: Allows resetting of others' tags
    default: false
  srpg.cmd.unlimitedammo:
    description: Allows access to '/unlimitedammo'
    default: true
  srpg.cmd.unride:
    description: Allows access to '/unride'
    default: false
  srpg.cmd.version:
    description: Allows access to '/srpg version'
    default: true
  srpg.staff:
    description: Displays a player as staff in '/stafflist'
    default: false
  srpg.update.notify:
    description: Allows notification of updates
    default: false